# week08/k8s/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: ecomm-secrets-w08e1
type: Opaque # Indicates arbitrary user-defined data
data:
  # PostgreSQL Credentials (for both Product DB and Order DB)
  POSTGRES_USER: "cG9zdGdyZXM=" # Base64 for 'postgres'
  POSTGRES_PASSWORD: "cG9zdGdyZXM=" # Base64 for 'postgres'

  # Azure Storage Account Credentials for Product Service image uploads
  # REPLACE WITH YOUR ACTUAL BASE64 ENCODED VALUES from your Azure Storage Account
  # Example: echo -n 'myblobstorageaccount' | base64
  AZURE_STORAGE_ACCOUNT_NAME: "c3RvcmFnZXNhcnRoYWs=" 
  # Example: echo -n 'your_storage_account_key_string' | base64
  AZURE_STORAGE_ACCOUNT_KEY: "bThoREo4ai9xYTlOTDhVR0RiWlpMRHdMNHdLRE8rL0JQakE0d1FXZEs0ZnUzUUplRlR3OHNUQ3o0M3NNV2k1MWtYNmJ3bUVwUTYxNitBU3R5ViticFE9PQ=="
